name: setup xmake
description: Set up a xmake environment and add it to the PATH
author: OpportunityLiu
branding:
  icon: play
  color: green

inputs:
  xmake-version:
    required: true
    default: latest
    description: The version to use. Should be a semver range or 'latest'. Or use [{repository}#]branch@{branch_name} to select a branch.
  actions-cache-folder:
    description: 'Directory to cache xmake in. This folder will go under $GITHUB_HOME (I.e. build dir) and be cached using @actions/cache.'
    default: ''
  actions-cache-key:
    description: The actions cache key.
    default: ''
  package-cache-folder:
    description: 'Directory to cache package in. This folder will go under $GITHUB_HOME (I.e. build dir) and be cached using @actions/cache.'
    default: ''
  package-cache-key:
    description: The packages cache key.
    default: ''
  package-cache-status:
    description: The packages cache status, e.g. load/save.
    default: ''
  build-cache-folder:
    description: 'Directory to cache build artifacts in. This folder will go under $GITHUB_HOME (I.e. build dir) and be cached using @actions/cache.'
    default: ''
  build-cache-key:
    description: The build cache key.
    default: ''
  build-cache-status:
    description: The build cache status, e.g. load/save.
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
