name: checkin

on:
  - push
  - pull_request

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 20
          pnpm-version: 8
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
      - name: release
        run: pnpm release
      - name: 'check for uncommitted changes'
        # Ensure no changes
        run: |
          git add .
          if ! git diff --cached --color=always --exit-code -- . ':!node_modules'; then
            echo "::error::Found changed files after build. Please run 'pnpm release' and check in all changes."
            exit 1
          fi
