name: test

on:
  - push

jobs:
  build:
    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.version }}-test
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [latest, branch@master, branch@dev]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@cache
        with:
          xmake-version: ${{ matrix.version }}
          actions-cache-folder: '.xmake-cache'
          build-cache: true
          build-cache-path: 'tests/sample/build/.build_cache'
          package-cache: true

      - name: Run tests
        run: |
          xmake --version
          cd tests/sample
          xmake -y -vD
          xmake run
