name: test

on:
  - push

jobs:
  build:
    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.version }}-test
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [latest, branch@master, branch@dev]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@test
        with:
          xmake-version: ${{ matrix.version }}
          actions-cache-folder: '.xmake-cache'
          build-cache-folder: '.xmake-build-cache'
          package-cache-folder: '.xmake-package-cache'

      - name: Run tests
        run: |
          xmake --version
          xmake create test
          cd test
          echo 'add_requires("libpng", {system = false})' >> xmake.lua
          echo 'add_packages("libpng")' >> xmake.lua
          xmake -v -y
          xmake run
